package edu.grinnell.csc207.soundsofsorting;

import java.util.ArrayList;
import java.util.List;

import edu.grinnell.csc207.soundsofsorting.events.*;

/**
 * A collection of sorting algorithms.
 */
public class Sorts {
    /**
     * Swaps indices <code>i</code> and <code>j</code> of array <code>arr</code>.
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to swap
     * @param i   the first index to swap
     * @param j   the second index to swap
     */
    public static <T> void swap(T[] arr, int i, int j) {
        T tmp = arr[i];
        arr[i] = arr[j];
        arr[j] = tmp;
    }

    /**
     * Sorts the array according to the bubble sort algorithm:
     * 
     * <pre>
     * [ unprocessed | i largest elements in order ]
     * </pre>
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> bubbleSort(T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();
        int j = 0;
        for (int n = 0; n < arr.length; n++) {
            for (int i = 0; i < arr.length - 1; i++) {
                j = i + 1;
                SortEvent<T> compareEvent = new CompareEvent(i, j);
                events.add(compareEvent);
                if (arr[i].compareTo(arr[j]) > 0) {
                    swap(arr, i, j);
                    SortEvent<T> swapEvent = new SwapEvent(i, j);
                    events.add(swapEvent);
                }
            }
        }
        return events;
    }

    /**
     * Sorts the array according to the selection sort algorithm:
     * 
     * <pre>
     * [ i smallest elements in order | unprocessed ]
     * </pre>
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> selectionSort(
            T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();
        for (int i = 0; i < arr.length - 1; i++) {
            int min = i;
            for (int j = i + 1; j < arr.length; j++) {
                SortEvent<T> compareEvent = new CompareEvent(i, j);
                events.add(compareEvent);
                if (arr[j].compareTo(arr[min]) < 0) {
                    min = j;
                }
            }
            swap(arr, i, min);
            SortEvent<T> swapEvent = new SwapEvent(i, min);
            events.add(swapEvent);

        }
        return events;
    }

    /**
     * Sorts the array according to the insertion sort algorithm:
     * 
     * <pre>
     * [ i elements in order | unprocessed ]
     * </pre>
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> insertionSort(
            T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();
        for (int i = 1; i < arr.length; i++) {
            T x = arr[i];
            int j = i - 1;

            SortEvent<T> compareEvent = new CompareEvent(i, j);
            events.add(compareEvent);
            while (j >= 0 && x.compareTo(arr[j]) < 0) {
                SortEvent<T> copyEvent = new CopyEvent(j + 1, arr[j]);
                events.add(copyEvent);
                arr[j + 1] = arr[j];
                j--;
            }

            SortEvent<T> copyEvent = new CopyEvent(j + 1, x);
            events.add(copyEvent);
            arr[j + 1] = x;
        }
        return events;
    }

    /**
     * Sorts the array according to the merge sort algorithm.
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */

    private static <T extends Comparable<? super T>> void merge(T[] arr, int left, int mid, int right, List<SortEvent<T>> events){
            int n1 = mid - left + 1;
            int n2 = right - mid;

            T L[] = (T[]) new Comparable[n1];
            T R[] = (T[]) new Comparable[n2];

            for (int i = 0; i < n1; ++i) {
                SortEvent<T> copyEvent = new CopyEvent(i, arr[left + i]);
                events.add(copyEvent);
                L[i] = arr[left + i];
            }

            for (int j = 0; j < n2; ++j) {
                SortEvent<T> copyEvent = new CopyEvent(j, arr[mid + 1 + j]);
                events.add(copyEvent);
                R[j] = arr[mid + 1 + j];
            }

            int i = 0, j = 0;

            int k = left;

            while (i < n1 && j < n2) {
                if (L[i].compareTo(R[j]) < 0) {
                    SortEvent<T> copyEvent = new CopyEvent(k, L[i]);
                    events.add(copyEvent);
                    arr[k] = L[i];
                    i++;
                } else {
                    SortEvent<T> copyEvent = new CopyEvent(k, R[j]);
                    events.add(copyEvent);
                    arr[k] = R[j];
                    j++;
                }
                k++;
            }

            while (i < n1) {
                SortEvent<T> copyEvent = new CopyEvent(k, L[i]);
                events.add(copyEvent);
                arr[k] = L[i];
                i++;
                k++;
            }

            while (j < n2) {
                SortEvent<T> copyEvent = new CopyEvent(k, R[j]);
                events.add(copyEvent);
                arr[k] = R[j];
                j++;
                k++;
            }
        }

     private static <T extends Comparable<? super T>> void mSort (T[] arr, int left, int right, List<SortEvent<T>> events) {
            if (left < right) {
                int mid = (left + right) / 2;

                mSort(arr, left, mid, events);
                mSort(arr, mid + 1, right, events);

                merge(arr, left, mid, right, events);
            }
        }

    public static <T extends Comparable<? super T>> List<SortEvent<T>> mergeSort(T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();
        mSort(arr, 0, arr.length - 1, events);
        return events;
    }

    public static <T extends Comparable<? super T>> int partition(T[] arr, int lo, int hi, List<SortEvent<T>> events) {
        T pivot = arr[hi];
        int i = lo - 1;

        for (int j = lo; j < hi; j++) {
            SortEvent<T> compareEvent = new CompareEvent(j, hi);
            events.add(compareEvent);
            if (arr[j].compareTo(pivot) < 0) {
                i++;
                SortEvent<T> swapEvent = new SwapEvent(i, j);
                events.add(swapEvent);
                swap(arr, i, j);
            }
        }

        SortEvent<T> swapEvent = new SwapEvent(i + 1, hi);
        events.add(swapEvent);
        swap(arr, i + 1, hi);

        return i + 1;
    }

    /**
     * Sorts the array according to the quick sort algorithm.
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> void qSort(T[] arr, int lo, int hi, List<SortEvent<T>> events) {
        if (lo < hi) {
            int pi = partition(arr, lo, hi, events);

            qSort(arr, lo, pi - 1, events);
            qSort(arr, pi, hi, events);
        }
    }

    public static <T extends Comparable<? super T>> List<SortEvent<T>> quickSort(T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();
        qSort(arr, 0, arr.length - 1, events);
        return events;
    }

    /**
     * Sorts the given array by applying the given events to it, in sequence.
     * 
     * @param events the sorting events to apply
     * @param arr    the array to sort
     */
    public static <T extends Comparable<? super T>> void eventSort(
            List<SortEvent<T>> events, T[] arr) {
        for (SortEvent<T> event : events) {
            event.apply(arr);
        }
    }
}
